apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization



# resources:
# - external-secrets_v0.4.4_Chart.yaml

# helmGlobals:
#   chartHome: charts
helmCharts:
- name: external-secrets
  releaseName: external-secrets
  # Commented in case have local helm chart.
  #version: 0.4.4
  #repo: https://charts.external-secrets.io
  namespace: external-secrets
  # valuesFile: devs-values.yaml