apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp01-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

