apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
   env: prod

helmGlobals:
  chartHome: ../../base/charts
helmCharts:
- name: external-secrets
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: prod-values.yaml