apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  org: cision-devops

resources:
- backend-deploy.yml
- backend-svc.yml
- demoapp01-deploy.yml
- demoapp01-svc.yml
- demoapp01-ingress.yml

# helmGlobals:
#   chartHome: charts
helmCharts:
- name: external-secrets
  releaseName: external-secrets
  namespace: external-secrets
  # Commented in case have local helm chart.
  # All available options 
  # https://cloud.google.com/anthos-config-management/docs/how-to/use-repo-kustomize-helm#supported_fields
  #version: 0.4.4
  #repo: https://charts.external-secrets.io
