apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
   env: dev
# resources:
# - ../base
# - dev-values.yaml
# bases:
# - ../base
#- ../base/external-secrets_v0.4.4_Chart.yaml
# resources:
# - dev-values.yaml
# - ../base/charts/external-secrets/Chart.yaml
helmGlobals:
  chartHome: ../base/charts
helmCharts:
- name: external-secrets
  releaseName: external-secrets
# # #   version: 0.4.4
# # #   # repo: https://charts.external-secrets.io
  namespace: external-secrets
  valuesFile: dev-values.yaml